### ISSUE TITLE
not a code issue but a question about efnet IRC

### ISSUE THREAD

**Issue by vn971** [geir54/android-sqrl#10]
Sorry, this is not a code issue but rather a question about efnet IRC.

The README file says the recommended IRC channel is #sqrl on efnet. However, I can't get there. I used 4 entries from the following list to try connect to:
    > http://www.efnet.org/?module=servers
all the servers failed for me, for various reasons. Could you please mention the server that works with less friction?
I use pidgin and I'm more or less familiar with IRC.

**Comment by sesam** [comment]
If you're not a "veteran" of IRC, then you probably want to start with a web-based client: http://lmgtfy.com/?q=efnet+webchat
Otherwise, you'll probably already have a shell account on a trusted "box" where you run your "screen" and whatnot.

**Comment by vn971** [comment]
@sesam the wrapping of IRC around `screen` or a web service isn't exactly what I was trying to solve.. Instead, I wanted to know a working address:port (and whether it should be used with SSL/SASL).

**Comment by sesam** [comment]
Ok, then sorry for assuming you had just dug out a irc client and started sporadically testing some servers and ports like most people do :-p.
Did you try choosing "EFnet" from a network list instead of going on a specific server?
Did you get a disconnect message from the IRC server(s) you tried?
Which irc client and OS are you connecting from?
Do you have identd active and passing through all relevant firewalls?
Tried disabling (horror) your firewall while testing?

Did you try connecting to minimally popular servers (disconnected reason: too many users / user count above limit / ...)?

Maybe the servers you tried were blocking or blocked from your connecting IP subnet. In the old days, irc servers often worked and when not, it was 99% the users fault not having activated identd or the builtin identd of mIRC. Nowadays I'd guess firewalling and ISP-level blocking of identd would be the primary cause of error. Especially since ircd (used to?) give very unclear error messages, hidden inside a WOT, when not identd response was the reason they disconnect or refuse connect.

It is likely impossible to produce "the list" of "working servers" because the top item on that list would get too many users. And, being full, would not belong on the list but only until 1 user disconnects...

So best advice: get a IRC client where you choose EFnet from a built-in list, or just go with web chat for now.
